# Site wide configuration


title: TERRA REF
locale: en_US
description: TERRA Phenotyping Reference Platform
logo: site-logo.png
search: true
url: http://terraref.ncsa.illinois.edu

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true

# Site owner
owner:
  name: David LeBauer; ARPA-E TERRA Reference Data and Computing Team
#  avatar: dlebauer-bw.jpg
  email: dlebauer@illinois.edu
  disqus-shortname: terraref
  twitter: terra_ref
  facebook: #username
  github: terraref
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-65745047-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
